version: "2"
linters:
  enable:
    - lll
  settings:
    lll:
      # max line length, lines longer will be reported. Default is 120.
      # '\t' is counted as 1 character by default, and can be changed with the tab-width option
      line-length: 120
      # tab width in spaces. Default to 1.
      tab-width: 4
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        text: "test files"
        linters:
          - lll

